alias ll="ls -l"
alias c="clear"
alias gst="git status"
alias gitu="git svn rebase"
alias gp="git pull --rebase"
alias db="mysql -u root -p"
alias gst="git status"
alias gs="git status"
alias gd="git diff"
alias glog="git log --oneline"
alias bec="bundle exec cucumber --tags ~@wip --tags ~@omniture --tags ~@manual $1"
alias ber="bundle exec rspec"
alias gdc="gd --cached"
alias rdms="rake db:migrate db:seed"
alias rdmst="rake db:migrate db:seed RAILS_ENV=test"
alias em="emacs . &"
alias cuke='bundle exec cucumber --tags ~@wip --tags ~@omniture --tags ~@manual $1
alias rp="rake push'
alias disp="xrandr --newmode "1680x1050_60.00"  146.25  1680 1784 1960 2240  1050 1053 1059 10"
alias t="ruby -Itest"
alias rev="awk '{out = $0 s out; s = RS} END {print out}'"
